services:
  db:
    container_name: lmDB
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data

  pgadmin:
    container_name: PgAdmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=9050
    ports:
      - "9050:9050"
volumes:
  data:
